pages = [{"l":"index.html#","e":false,"i":"","n":"Bolster","t":"Bolster","d":"","k":"static","x":""},
{"l":"bolster/security.html#","e":false,"i":"","n":"bolster.security","t":"bolster.security","d":"","k":"package","x":""},
{"l":"bolster/security/Permission.html#","e":false,"i":"","n":"Permission","t":"Permission","d":"bolster.security","k":"trait","x":""},
{"l":"bolster/security/Permission.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"bolster.security.Permission","k":"def","x":""},
{"l":"bolster/security/Permission$.html#","e":false,"i":"","n":"Permission","t":"Permission","d":"bolster.security","k":"object","x":""},
{"l":"bolster/security/Permission$.html#apply-fffffd77","e":false,"i":"","n":"apply","t":"apply(name: String): Permission","d":"bolster.security.Permission","k":"def","x":""},
{"l":"bolster/security/Permission$.html#toSet-5e8","e":false,"i":"","n":"toSet","t":"toSet(names: Iterable[String]): Set[Permission]","d":"bolster.security.Permission","k":"def","x":""},
{"l":"bolster/security/Permission$.html#toSet-ffe","e":false,"i":"","n":"toSet","t":"toSet(one: String, more: String*): Set[Permission]","d":"bolster.security.Permission","k":"def","x":""},
{"l":"bolster/security/Permission$.html#unapply-fffff739","e":false,"i":"","n":"unapply","t":"unapply(perm: Permission): Option[String]","d":"bolster.security.Permission","k":"def","x":""},
{"l":"bolster/security/RootContext$.html#","e":false,"i":"","n":"RootContext","t":"RootContext extends SecurityContext","d":"bolster.security","k":"object","x":""},
{"l":"bolster/security/RootContext$.html#all-fffffba4","e":false,"i":"","n":"all","t":"all[T](perms: Set[Permission])(op: => T): T","d":"bolster.security.RootContext","k":"def","x":""},
{"l":"bolster/security/RootContext$.html#all-fffffa4d","e":false,"i":"","n":"all","t":"all[T](one: Permission, more: Permission*)(op: => T): T","d":"bolster.security.RootContext","k":"def","x":""},
{"l":"bolster/security/RootContext$.html#any-fffffba4","e":false,"i":"","n":"any","t":"any[T](perms: Set[Permission])(op: => T): T","d":"bolster.security.RootContext","k":"def","x":""},
{"l":"bolster/security/RootContext$.html#any-fffffa4d","e":false,"i":"","n":"any","t":"any[T](one: Permission, more: Permission*)(op: => T): T","d":"bolster.security.RootContext","k":"def","x":""},
{"l":"bolster/security/RootContext$.html#apply-fffff498","e":false,"i":"","n":"apply","t":"apply[T](perm: Permission)(op: => T): T","d":"bolster.security.RootContext","k":"def","x":""},
{"l":"bolster/security/RootContext$.html#test-5e4","e":false,"i":"","n":"test","t":"test(perm: Permission): Boolean","d":"bolster.security.RootContext","k":"def","x":""},
{"l":"bolster/security/RootContext$.html#testAll-fffff7f2","e":false,"i":"","n":"testAll","t":"testAll(perms: Set[Permission]): Boolean","d":"bolster.security.RootContext","k":"def","x":""},
{"l":"bolster/security/RootContext$.html#testAll-fffffa99","e":false,"i":"","n":"testAll","t":"testAll(one: Permission, more: Permission*): Boolean","d":"bolster.security.RootContext","k":"def","x":""},
{"l":"bolster/security/RootContext$.html#testAny-fffff7f2","e":false,"i":"","n":"testAny","t":"testAny(perms: Set[Permission]): Boolean","d":"bolster.security.RootContext","k":"def","x":""},
{"l":"bolster/security/RootContext$.html#testAny-fffffa99","e":false,"i":"","n":"testAny","t":"testAny(one: Permission, more: Permission*): Boolean","d":"bolster.security.RootContext","k":"def","x":""},
{"l":"bolster/security/RootContext$.html#toString-0","e":false,"i":"","n":"toString","t":"toString: String","d":"bolster.security.RootContext","k":"val","x":""},
{"l":"bolster/security/SecurityContext.html#","e":false,"i":"","n":"SecurityContext","t":"SecurityContext","d":"bolster.security","k":"trait","x":""},
{"l":"bolster/security/SecurityContext.html#all-fffffba4","e":false,"i":"","n":"all","t":"all[T](perms: Set[Permission])(op: => T): T","d":"bolster.security.SecurityContext","k":"def","x":""},
{"l":"bolster/security/SecurityContext.html#all-fffffa4d","e":false,"i":"","n":"all","t":"all[T](one: Permission, more: Permission*)(op: => T): T","d":"bolster.security.SecurityContext","k":"def","x":""},
{"l":"bolster/security/SecurityContext.html#any-fffffba4","e":false,"i":"","n":"any","t":"any[T](perms: Set[Permission])(op: => T): T","d":"bolster.security.SecurityContext","k":"def","x":""},
{"l":"bolster/security/SecurityContext.html#any-fffffa4d","e":false,"i":"","n":"any","t":"any[T](one: Permission, more: Permission*)(op: => T): T","d":"bolster.security.SecurityContext","k":"def","x":""},
{"l":"bolster/security/SecurityContext.html#apply-fffff498","e":false,"i":"","n":"apply","t":"apply[T](perm: Permission)(op: => T): T","d":"bolster.security.SecurityContext","k":"def","x":""},
{"l":"bolster/security/SecurityContext.html#test-5e4","e":false,"i":"","n":"test","t":"test(perm: Permission): Boolean","d":"bolster.security.SecurityContext","k":"def","x":""},
{"l":"bolster/security/SecurityContext.html#testAll-fffff7f2","e":false,"i":"","n":"testAll","t":"testAll(perms: Set[Permission]): Boolean","d":"bolster.security.SecurityContext","k":"def","x":""},
{"l":"bolster/security/SecurityContext.html#testAll-fffffa99","e":false,"i":"","n":"testAll","t":"testAll(one: Permission, more: Permission*): Boolean","d":"bolster.security.SecurityContext","k":"def","x":""},
{"l":"bolster/security/SecurityContext.html#testAny-fffff7f2","e":false,"i":"","n":"testAny","t":"testAny(perms: Set[Permission]): Boolean","d":"bolster.security.SecurityContext","k":"def","x":""},
{"l":"bolster/security/SecurityContext.html#testAny-fffffa99","e":false,"i":"","n":"testAny","t":"testAny(one: Permission, more: Permission*): Boolean","d":"bolster.security.SecurityContext","k":"def","x":""},
{"l":"bolster/security/SecurityViolation.html#","e":false,"i":"","n":"SecurityViolation","t":"SecurityViolation(message: String) extends RuntimeException","d":"bolster.security","k":"class","x":""},
{"l":"bolster/security/UserContext.html#","e":false,"i":"","n":"UserContext","t":"UserContext extends SecurityContext","d":"bolster.security","k":"trait","x":""},
{"l":"bolster/security/UserContext.html#grant-fffff105","e":false,"i":"","n":"grant","t":"grant(perms: Set[Permission]): UserContext","d":"bolster.security.UserContext","k":"def","x":""},
{"l":"bolster/security/UserContext.html#grant-b7e","e":false,"i":"","n":"grant","t":"grant(one: Permission, more: Permission*): UserContext","d":"bolster.security.UserContext","k":"def","x":""},
{"l":"bolster/security/UserContext.html#permissions-0","e":false,"i":"","n":"permissions","t":"permissions: Set[Permission]","d":"bolster.security.UserContext","k":"def","x":""},
{"l":"bolster/security/UserContext.html#revoke-fffff105","e":false,"i":"","n":"revoke","t":"revoke(perms: Set[Permission]): UserContext","d":"bolster.security.UserContext","k":"def","x":""},
{"l":"bolster/security/UserContext.html#revoke-b7e","e":false,"i":"","n":"revoke","t":"revoke(one: Permission, more: Permission*): UserContext","d":"bolster.security.UserContext","k":"def","x":""},
{"l":"bolster/security/UserContext$.html#","e":false,"i":"","n":"UserContext","t":"UserContext","d":"bolster.security","k":"object","x":""},
{"l":"bolster/security/UserContext$.html#apply-fffff105","e":false,"i":"","n":"apply","t":"apply(perms: Set[Permission]): UserContext","d":"bolster.security.UserContext","k":"def","x":""},
{"l":"bolster/security/UserContext$.html#apply-382","e":false,"i":"","n":"apply","t":"apply(perms: Seq[Permission]): UserContext","d":"bolster.security.UserContext","k":"def","x":""},
{"l":"bolster/security/UserContext$.html#apply-b7e","e":false,"i":"","n":"apply","t":"apply(one: Permission, more: Permission*): UserContext","d":"bolster.security.UserContext","k":"def","x":""},
{"l":"bolster/security/UserContext$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: UserContext","d":"bolster.security.UserContext","k":"def","x":""},
{"l":"bolster/security/UserContext$.html#unapply-394","e":false,"i":"","n":"unapply","t":"unapply(security: UserContext): Option[Set[Permission]]","d":"bolster.security.UserContext","k":"def","x":""}];